
// create database


CREATE TABLE IF NOT EXISTS (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
username  VARCHAR() NOT NULL,
Firstname  VARCHAR() NOT NULL,
Lastname  VARCHAR() NOT NULL,
email  VARCHAR() NOT NULL,
Password  VARCHAR() NOT NULL,
pubdate TIMESTAMP,
ipaddress VARCHAR()
); 

CREATE TABLE IF NOT EXISTS page (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
pageurl  VARCHAR() NOT NULL,
title SMALLTEXT,
description SMALLTEXT,
content TEXT,
pubdate TIMESTAMP,
ipaddress VARCHAR()
);


CREATE TABLE IF NOT EXISTS (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
posturl  VARCHAR() NOT NULL,
title SMALLTEXT,
description SMALLTEXT,
categoryId VARCHAR() NOT NULL,
imageuel VARCHAR() NOT NULL,
content TEXT,
pubdate TIMESTAMP,
ipaddress VARCHAR()
); 
   
CREATE TABLE IF NOT EXISTS user (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
firstname  VARCHAR() NOT NULL,
lastname  VARCHAR() NOT NULL,
username VARCHAR() NOT NULl UNIQUE,
email  VARCHAR() NOT NULL UNIQUE,
password VARCHAR() NOT NULL,
reseturl VARCHAR() NOT NULl,
pubdate TIMESTAMP,
ipaddress VARCHAR()
);






