
CREATE TABLE IF NOT EXISTS admin (
id INT(15) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
username  VARCHAR(255) NOT NULL,
firstname  VARCHAR(255) NOT NULL,
lastname  VARCHAR(255) NOT NULL,
email  VARCHAR(255) NOT NULL,
Password  VARCHAR(255) NOT NULL,
pubdate TIMESTAMP,
ipaddress VARCHAR(255)
); 

CREATE TABLE IF NOT EXISTS page (
id INT(15) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
pageurl VARCHAR(255) NOT NULL,
title TEXT,
description TEXT,
content TEXT,
pubdate TIMESTAMP,
ipaddress VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS post (
id INT(15) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
posturl VARCHAR(255) NOT NULL,
title TEXT,
description TEXT,
categoryId VARCHAR(255) NOT NULL,
imageuel VARCHAR(255) NOT NULL,
content TEXT,
pubdate TIMESTAMP,
ipaddress VARCHAR(255)
); 
   
CREATE TABLE IF NOT EXISTS user (
id INT(15) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
firstname VARCHAR(255) NOT NULL,
lastname VARCHAR(255) NOT NULL,
username VARCHAR(255) NOT NULl UNIQUE,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
reseturl VARCHAR(255) NOT NULl,
pubdate TIMESTAMP,
ipaddress VARCHAR(255)
);






