DROP TABLE IF EXISTS userrole;
CREATE TABLE userrole (
id INT(15) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
rolename Text,
canCreate ENUM('0','1') DEFAULT '0',
canRead ENUM('0','1') DEFAULT '0',
canUpdate ENUM('0','1') DEFAULT '0',
canDelete ENUM('0','1') DEFAULT '0',
canApprove ENUM('0','1') DEFAULT '0',
canUpgrade ENUM('0','1') DEFAULT '0',
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
ipaddress VARCHAR(255) NOT NULL
); 


DROP TABLE IF EXISTS userdata;
CREATE TABLE userdata(
id INT(15) UNSIGNED  NOT NULL AUTO_INCREMENT PRIMARY KEY,
userroleid INT(15) UNSIGNED NOT NULL DEFAULT 1,
username VARCHAR(255) NOT NULl,
firstname VARCHAR(255) NOT NULL,
lastname VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
status ENUM('0','1') NOT NULl DEFAULT '0',
reseturl VARCHAR(256),
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
biography TEXT DEFAULT "",
ipaddress VARCHAR(255) NOT NULL,
CONSTRAINT userdata_FK1 FOREIGN KEY (userroleid) REFERENCES userrole(id) 
);

DROP TABLE IF EXISTS page;
CREATE TABLE page (
id INT(15) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
url VARCHAR(255) NOT NULL UNIQUE,
title TEXT,
description TEXT,
content TEXT,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
ipaddress VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS category;
CREATE TABLE category (
id INT(15) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL UNIQUE,
description  VARCHAR(255) NOT NULL,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
ipaddress VARCHAR(255) NOT NULL
); 

DROP TABLE IF EXISTS media;
CREATE TABLE media (
id INT(15) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
url VARCHAR(255) NOT NULL UNIQUE,
ext VARCHAR(10) NOT NULL,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
ipaddress VARCHAR(255) NOT NULL
);


DROP TABLE IF EXISTS post;
CREATE TABLE post (
id INT(15) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
url VARCHAR(255) NOT NULL UNIQUE,
title TEXT,
description TEXT,
content TEXT,
category_id INT(15) UNSIGNED NOT NULL,
media_id INT(15) UNSIGNED NOT NULL,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
ipaddress VARCHAR(255) NOT NULL,
CONSTRAINT posts_FK1 FOREIGN KEY (category_id) REFERENCES category(id) ON UPDATE CASCADE
CONSTRAINT posts_FK2 FOREIGN KEY (media_id) REFERENCES media(id) ON UPDATE CASCADE
); 

DROP TABLE IF EXISTS comment;
CREATE TABLE comment(
id INT(15) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(256) NOT NULL,
email VARCHAR(255) NOT NULL,
website VARCHAR(256),
post_id INT(15) UNSIGNED NOT NULL,
comment TEXT NOT NULL,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
ipaddress VARCHAR(255) NOT NULL,
CONSTRAINT comment_FK1 FOREIGN KEY (post_id) REFERENCES post (id)  ON UPDATE CASCADE
);


INSERT INTO `userrole` (`rolename`,`canCreate`,`canRead` ,`canUpdate`,`canDelete`,`canApprove`,`canUpgrade`) VALUES
('admin','1','1','1','1','1','0'),('author','1','1','1','0','0','1'),('user','0','1','0','0','0','1');




  







