
DROP TABLE IF EXISTS users;
CREATE TABLE users (
id INT(15) UNSIGNED  NOT NULL AUTO_INCREMENT PRIMARY KEY,
firstname VARCHAR(255) NOT NULL,
lastname VARCHAR(255) NOT NULL,
username VARCHAR(255) NOT NULl,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
status ENUM('0','1') NOT NULl DEFAULT '0',
reseturl text,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
ipaddress VARCHAR(255)
);

DROP TABLE IF EXISTS staticpages;
CREATE TABLE staticpages (
id INT(15) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
url VARCHAR(255) NOT NULL UNIQUE,
title TEXT,
description TEXT,
content TEXT,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
ipaddress VARCHAR(255)
);

   

DROP TABLE IF EXISTS category;
CREATE TABLE category (
id INT(15) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
description  VARCHAR(255) NOT NULL,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
ipaddress VARCHAR(255)
); 

DROP TABLE IF EXISTS media;
CREATE TABLE media (
id INT(15) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
url VARCHAR(255) NOT NULL
);



DROP TABLE IF EXISTS author;
CREATE TABLE author (
id INT(15) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
biography TEXT,
user_id INT(15) UNSIGNED NOT NULL,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
ipaddress VARCHAR(255),
CONSTRAINT author_FK1 FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE
); 


DROP TABLE IF EXISTS dynamicpages;
CREATE TABLE dynamicpages (
id INT(15) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
url VARCHAR(255) NOT NULL,
title TEXT,
description TEXT,
content TEXT,
category_id INT(15) UNSIGNED NOT NULL,
media_id INT(15) UNSIGNED NOT NULL,
author_id INT(15) UNSIGNED NOT NULL,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
ipaddress VARCHAR(255) NOT NULL,
CONSTRAINT dynamicpages_FK1 FOREIGN KEY (category_id) REFERENCES category(id) ON UPDATE CASCADE,
CONSTRAINT dynamicpages_FK2 FOREIGN KEY (media_id) REFERENCES media(id) ON UPDATE CASCADE,
CONSTRAINT dynamicpages_FK4 FOREIGN KEY (author_id) REFERENCES author(id) ON UPDATE CASCADE
); 

DROP TABLE IF EXISTS comments;
CREATE TABLE comments(
id INT(15) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
dynamicpages_id INT(15) UNSIGNED NOT NULL,
comments TEXT,
CONSTRAINT comments_FK1 FOREIGN KEY (dynamicpages_id) REFERENCES dynamicpages (id)  ON UPDATE CASCADE
);







  







